# Path to word embeddings
embeddings: data/collobert/embeddings50.txt

# Path to train and test sentence pairs and labels
dataset: data/task2/images

# Max number of epochs
epochs: 10

# Word labels type:
#  - int - labels are one-hot (rounded to closest integer)
#  - approx - labels are approximated between two closest integers

label_rounding: approx

# Model specification:

# Input type (sentence or tree)
input_type: sentence
num_rnn_layers: 1
