# Embeddings type
embeddings: dict

# Path to word embeddings
embeddings_path: data/collobert/embeddings50.txt

# Path to train and test sentence pairs and labels
dataset: data/task1/MSRvid

# Max number of epochs
epochs: 15

# Word labels type:
#  - int - labels are one-hot (rounded to closest integer)
#  - approx - labels are approximated between two closest integers

label_rounding: approx

# Model specification:
model: vrnn

# Input type (sentence or tree)
input_type: tree
num_rnn_layers: 2
